apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  namespace: airflow-dbt
spec:
  storageClassName: local-path
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/airflow/logs"
